trigger:
- main

pool:
  name: 'scaffold-py'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pylint hello.py
  displayName: 'Run lint'

- script: |
    pytest
  displayName: 'Run tests'

# test
