trigger:
- main

pool:
  name: 'scaffold-py '    # Nome do pool onde o agente auto-hospedado está configurado

variables:
  containerRegistry: 'jorgetrivilin'  # Você também pode definir isso como uma variável de ambiente se quiser

steps:
- task: DockerInstaller@0
  displayName: 'Install Docker'

- script: |
    echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
    docker pull $(containerRegistry)/scaffold-py:latest
  displayName: 'Login to Docker and Pull Docker image'

- script: |
    docker run $(containerRegistry)/scaffold-py:latest pylint hello.py
  displayName: 'Run lint'

- script: |
    docker run $(containerRegistry)/scaffold-py:latest pytest
  displayName: 'Run tests'
