trigger:
- main

pool:
  name: 'scaffold-py'

variables:
- group: 'docker_variables'

steps:
- task: DockerInstaller@0
  displayName: 'Install Docker'

steps:
- script: |
    echo "Disabling Docker credentials store..."
    mkdir -p ~/.docker
    echo '{"credsStore":""}' > ~/.docker/config.json
  displayName: 'Disable Docker Credentials Store'

- script: |
    echo "Logging into Docker..."
    echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin --config ~/.docker
    docker pull $(CONTAINER_REGISTRY)/scaffold-py:latest
  displayName: 'Login to Docker and Pull Docker image'

- script: |
    docker run $(CONTAINER_REGISTRY)/scaffold-py:latest pylint hello.py
  displayName: 'Run lint'

- script: |
    docker run $(CONTAINER_REGISTRY)/scaffold-py:latest pytest
  displayName: 'Run tests'
