trigger:
- main

pool:
  name: 'scaffold-py'

variables:
  containerRegistry: 'jorgetrivilin'

steps:
- task: DockerInstaller@0
  displayName: 'Install Docker'

- script: |
    echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
    docker pull $(containerRegistry)/scaffold-py:latest
  displayName: 'Login to Docker and Pull Docker image'
  env:
    DOCKER_USERNAME: $(DOCKER_USERNAME)
    DOCKER_PASSWORD: $(DOCKER_PASSWORD)

- script: |
    docker run $(containerRegistry)/scaffold-py:latest pylint hello.py
  displayName: 'Run lint'

- script: |
    docker run $(containerRegistry)/scaffold-py:latest pytest
  displayName: 'Run tests'
