trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

resources:
  containers:
  - container: python
    image: jorgetrivilin/scaffold-py:latest
    endpoint: DockerHubConnection

steps:
- task: DockerInstaller@0
  displayName: 'Install Docker'

- script: |
    docker pull $(containerRegistry)/scaffold-py:latest
  displayName: 'Pull Docker image'

- script: |
    docker run $(containerRegistry)/scaffold-py:latest pylint hello.py
  displayName: 'Run lint'

- script: |
    docker run $(containerRegistry)/scaffold-py:latest pytest
  displayName: 'Run tests'
