trigger:
- main

pool:
  name: 'scaffold-py'  # Nome do agent pool

steps:
- script: |
    python3.11 -m venv myenv
    source myenv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Setup Python environment and install dependencies'

- script: |
    source myenv/bin/activate
    pylint hello.py
  displayName: 'Run lint'

- script: |
    source myenv/bin/activate
    pytest
  displayName: 'Run tests'
