steps:
  - name: 'python:3.8'
    id: 'Install dependencies'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint

  - name: 'python:3.8'
    id: 'Lint'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pylint hello.py
    waitFor:
      - 'Install dependencies'

  - name: 'python:3.8'
    id: 'Test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pytest
    waitFor:
      - 'Install dependencies'

artifacts:
  objects:
    location: gs://scaffold-py/artifacts/
    paths:
      - 'workspace/pip/**/*'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  substitutionOption: ALLOW_LOOSE
  dynamicSubstitutions: true

timeout: '600s'

logsBucket: gs://scaffold-py/logs
