steps:
  - name: 'gcr.io/turnkey-mender-430717-t7/my-custom-container'
    entrypoint: 'bash'
    args: ['-c', 'pylint hello.py']

  - name: 'gcr.io/turnkey-mender-430717-t7/my-custom-container'
    entrypoint: 'bash'
    args: ['-c', 'pytest']

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  substitutionOption: ALLOW_LOOSE
  dynamicSubstitutions: true

timeout: '600s'

logsBucket: gs://scaffold-py/logs
