steps:
  - name: 'python:3.8'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip &&
        pip install -r requirements.txt

  - name: 'python:3.8'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        make lint

  - name: 'python:3.8'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        make test
