steps:
  - name: 'python:3.8'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
        make lint
        make test

logsBucket: 'gs://scaffold-py'
