name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Lint code
      run: |
        make lint
    - name: Test code
      run: |
        make test
    - name: Format code
      run: |
        make format
        git config --global user.email "jorge.trivilin@gmail.com"
        git config --global user.name "Jorge Trivilin"
        git add hello.py
        git commit -m "Auto-format code"
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        git push
