name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with pylint
        run: |
          pip install pylint
          pylint hello.py
      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/scaffold-py:main
          labels:
            org.opencontainers.image.title: scaffold-py
            org.opencontainers.image.description: The Scaffold-Py repository is designed to provide a structured starting point for Python projects, with a focus on maintaining high code quality and facilitating continuous integration. 
            org.opencontainers.image.url: https://github.com/jorge-trivilin/scaffold-py
            org.opencontainers.image.source: https://github.com/jorge-trivilin/scaffold-py
            org.opencontainers.image.version: main
            org.opencontainers.image.created: ${{ runner.os }}
            org.opencontainers.image.revision: ${{ github.sha }}
            org.opencontainers.image.licenses:
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}/scaffold-py
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
